# Generated by Django 4.1.5 on 2023-01-31 10:22

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_comprador", models.CharField(max_length=60)),
                ("contato_comprador", models.CharField(max_length=20)),
                (
                    "valor_total",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.1)]
                    ),
                ),
                ("cep_entrega", models.CharField(max_length=9)),
                ("numero_endereco", models.PositiveIntegerField()),
                ("itens", models.JSONField()),
                ("entregue", models.BooleanField(default=False)),
                ("data_pedido", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
