# Generated by Django 4.1.5 on 2023-01-31 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="data_entrega",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
