# Generated by Django 4.1.5 on 2023-02-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_pedido_data_entrega"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="mensagem",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
