# Generated by Django 4.1.5 on 2023-01-28 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doce",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("descricao", models.TextField(max_length=255)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("BRIGADEIRO", "Brigadeiro"),
                            ("BOLO", "Bolo"),
                            ("PUDIM", "Pudim"),
                            ("MOUSSE", "Mousse"),
                            ("PAVÊ", "Pavê"),
                            ("SORVETE", "Sorvete"),
                            ("AÇAÍ", "Açaí"),
                            ("BEIJINHO", "Beijinho"),
                            ("BROWNIE", "Brownie"),
                            ("OUTROS", "Outros"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "preco",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.1)]
                    ),
                ),
                ("foto", models.ImageField(blank=True, upload_to="fotos/%Y/%m/%d/")),
            ],
        ),
    ]
