# Generated by Django 4.1.5 on 2023-01-31 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("confeitaria", "0003_pedidos"),
    ]

    operations = [
        migrations.RenameModel(old_name="Pedidos", new_name="Pedido",),
    ]
