# Generated by Django 4.1.5 on 2023-01-31 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("confeitaria", "0004_rename_pedidos_pedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="data_pedido",
            field=models.DateField(
                default=datetime.datetime(2023, 1, 30, 21, 22, 1, 749853)
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="entregue",
            field=models.BooleanField(default=False),
        ),
    ]
