# Generated by Django 4.1.5 on 2023-01-31 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("confeitaria", "0005_pedido_data_pedido_pedido_entregue"),
    ]

    operations = [
        migrations.DeleteModel(name="Pedido",),
    ]
